# -*- coding: utf-8 -*-
"""Azərbaycan (və ümumi türk) adları üzrə cins lüğəti.

Açar formatı: BÖYÜK hərflər, İ -> I normallaşdırılıb.
"""


def norm(name: str) -> str:
    return str(name).strip().upper().replace("İ", "I")


MALE = frozenset(
    norm(w)
    for w in """
    ABBAS ABDURRAHMAN ABUTURAB ADƏM ADİL ADIL AĞA AĞASI AĞALAR AKİF ALTAN ALTAY
    AMİN AMIN ANAR AQİL ARAZ ARİF ARIF ASİF ASIF ASLAN AYDIN AYAZ AYXAN
    BAHADIR BƏHRAM BƏHRUZ BƏXTİYAR BAĞIR BERAT BURAK
    CABBAR CAHİD CAHID CANPOLAD CAVAD CAVANŞİR CAVİD CAVID CƏFƏR CƏLAL CƏMİL
    CEYHUN ÇİNGİZ ÇINGIZ CÜNEYT CUNEYT
    DADAŞ DAVUD DEMİR DILQAM
    EHTİRAM EHTIRAM ELBRUS ELCAN ELÇİN ELDAR ELGÜN ELMAR ELMİR ELMIR ELNUR
    ELŞAD ELŞƏN ELVİN ELVIN EMİL EMİN ERTUĞRUL ƏRTOĞRUL EŞQİN EŞQIN EXTİYAR
    FAIQ FƏRİD FƏRID FARIZ FARUQ FƏRHAD FEYRUZ FİKRƏT FİRDOVSİ FİRUDİN FUAD FÜZULİ
    ƏBƏFƏZLABBAS ƏBÜLFƏZ ƏLI ƏLIƏKBƏR ƏLIƏSGƏR ƏMRAH ƏZİZ ƏZIZ
    QABİL QADİR QƏDİR QƏZƏNFƏR QİSMƏT QOŞQAR QULU QÜDRƏT QASIM
    HABİL HABIL HAFİZ HƏMID HƏMİD HARUN HƏSƏN HÜSEYN HÜSEYIN
    XALİD XALID XALIQ XƏYYAM XƏLİL XANLAR XƏYAL
    İBRAHİM İBRAHIM İLQAR İLKİN İLYAS İMAMƏLİ İRFAN İSA İSMAYIL İSLAM İZZƏT
    KAMAL KAMİL KAMIL KAZIM KƏNAN KƏRİM KƏRIM
    LOĞMAN
    MAHİR MAİS MALİK MALIK MƏHƏMMƏD MUHƏMMƏD MƏHƏMMƏDƏLİ MƏHƏRRƏM MEHDİ MEHMAN
    METE MİKAYIL MİRƏBƏLFƏZ MİRHADİ MİRKAMİL MİRKƏNAN MİRYUSİF MİRZƏ MURAD MUSTAFA
    MÜRVƏT MUSA
    NAMİQ NATİQ NAZİM NAZİR NİCAT NIHAD NIHAT NURAN NURLAN
    OKTAY ORXAN ÖMƏR
    PAŞA PƏNAH PƏRVİZ
    RAĞİF RAHİL RAMAZAN RAMİL RAMİN RASİM RAUF RAUL RƏCƏB RƏŞAD RƏSUL RƏVAN RİAD
    RİZVAN RUSLAN RÜSTƏM RÜFƏT RÖVŞƏN RZA
    SABİR SABIR SADIQ SAHİB SALEH SƏCCAD SƏCCAT SƏİD SƏID SƏMƏD SƏNAN SƏRXAN
    SƏYYAD SAMİR SAMIR SEYMUR SÜBHAN SÜLEYMAN SULTAN SULTANSƏNCƏR
    ŞAHİN ŞAMİL ŞƏMS ŞƏMSİ ŞİRVAN ŞÜKÜR
    TAHİR TAİR TƏBRİZ TƏHMASİB TELMAN TƏRLAN TOĞRUL TUNAR TURAL
    ÜMİD ÜMID UĞUR UTARİD
    VAHİD VALEH VASİF VÜQAR VÜSAL
    YAQUB YAŞAR YAZDAN YUSİF YUSIF
    ZABİL ZABIL ZAFƏR ZAKİR ZAMİQ ZAUR ZÖHRAB
    """.split()
)

FEMALE = frozenset(
    norm(w)
    for w in """
    ALMAZ AYAN AYDAN AYGÜN AYLİN AYLIN AYNUR AYSEL AYSU AYTAC AYTƏN AYŞƏN AYSUN
    BAHAR BANU
    CANUR CƏNNƏT
    DİLƏK DILƏK DƏNİZ DİLARƏ DUYĞU
    EBRAR ELİF
    ƏFSANƏ ƏSMƏR ƏZİZƏ
    FATİMƏ FİDAN
    GÜLAY GÜLƏR GÜLNAR GÜLNAZ GÜLSÜM GÜLŞƏN GÜLYAZ GÜNAY
    HƏQİQƏT HƏVVA HİCRAN
    XATİRƏ XƏDİCƏ XƏDİCƏXANIM
    İNCİ İRADƏ İZZƏTXANIM
    KƏMALƏ KÖNÜL
    LALƏ LAMİYƏ LƏMAN LEYLA
    MƏDİNƏ MƏLAHƏT MƏLƏK MƏRCAN MƏRYƏM MƏSUMƏ MƏTANƏT MEHRİBAN MİRAY MÜJGAN
    MÜNƏVVƏR
    NAİLƏ NARIN NARINC NATƏVAN NƏFİSƏ NƏRGİZ NƏRGIZ NƏRMİN NƏZRİN NİGAR NİLAY NUR
    NURANƏ NÜŞABƏ NURAY
    QUMRU
    RƏFİQƏ RƏNA RƏVŞƏNƏ REYHAN RÖYA RÜBAB RÜQƏYYƏ
    SƏDƏF SƏBİNƏ SƏKİNƏ SƏMA SƏMAYƏ SELCAN SELEN SEVGİ SEVGİM SEVİNC SEVINC
    SİNARƏ SONA SƏNƏM SÜSƏN
    ŞƏBNƏM ŞƏLALƏ
    TACLI TƏHMİNƏ TÜNZALƏ
    ULDÜZ ÜLVİYYƏ
    VƏFA
    YEGANƏ YEGANEH
    ZEMFİRA ZEYNƏB ZİBA ZƏHRƏ ZƏHRƏXANIM ZƏRİFƏ
    """.split()
)